#!/bin/bash

WGETLIST="supervisor.tar.xz"
MD5SUMLIST="dontverify"
REQUIRES="python2"

###############################################
installation() { # INSTALLING SYSTEM SOFTWARE #
###############################################

cp -r ../supervisor-3.1.3 ${FAKEROOT}/opt/ 

cp -r usr ${FAKEROOT}/
cp -r etc ${FAKEROOT}/opt/

ln -s /etc/init.d/supervisor ${FAKEROOT}/etc/rc.d/rc5.d/S35supervisor 

#################
} # END OF FILE #
#################

